In [1]:
import pandas as pd
from pymongo import MongoClient, errors
from flask import jsonify
import pandas as pd
from datetime import date, timedelta, datetime
import os

In [48]:
PATH = "http://10.3.100.24/ScadaData/er_web/"

startDateObj = datetime.strptime('2023-08-17', "%Y-%m-%d")
endDateObj = datetime.strptime('2023-08-17', "%Y-%m-%d")

df={}

for date_val in pd.date_range(date(startDateObj.year, startDateObj.month, startDateObj.day), date(endDateObj.year, endDateObj.month, endDateObj.day)):
    try:
        FILE = "http://10.3.100.24/ScadaData/er_web/ER_THERMAL_GEN_{}.xlsx".format(date_val.strftime("%d%m%Y"))
        df = pd.read_excel(FILE, sheet_name='DATA')
        
        df = df.drop(1)
        
        df = df.drop(columns=['Unnamed: 0'])[0:1442]
        
        df.columns = df.iloc[0]
        
        df = df.drop(0)
        
        # Drop all columns after 'ER_Total'
        if 'ER_Total' in df.columns:
            df = df.loc[:, :'ER_Total']
        
        col_name = [col + " MW" for col in df.columns.tolist()]
        
        df.columns = col_name
        
        df.index = pd.date_range(date_val, date_val + timedelta(days=1), freq='1min')[:-1]

        print(df)
                
    except:
        print('Generator File read problem', date_val)

                    Barauni TPS  MW Muzaffarpur TPS  MW BH_THERMAL MW  \
2023-08-17 00:00:00      227.477264                   0    227.477264
2023-08-17 00:01:00      227.477264                   0    227.477264
2023-08-17 00:02:00      227.477264                   0    227.477264
2023-08-17 00:03:00      227.477264                   0    227.477264
2023-08-17 00:04:00      227.477264                   0    227.477264
...                             ...                 ...           ...
2023-08-17 23:55:00               0                   0             0
2023-08-17 23:56:00               0                   0             0
2023-08-17 23:57:00               0                   0             0
2023-08-17 23:58:00               0                   0             0
2023-08-17 23:59:00               0                   0             0

                    BIHAR HYDRO MW BIHAR SOLAR MW Bihar CPP+OTHERS MW  \
2023-08-17 00:00:00              0      28.686443        -1645.805054
2023-08-17 00:01:00              0      28.686443        -1645.878784
2023-08-17 00:02:00              0      28.686443        -1651.103516
2023-08-17 00:03:00              0      28.686443        -1643.383667
2023-08-17 00:04:00              0      28.686443        -1646.193726
...                            ...            ...                 ...
2023-08-17 23:55:00              0      28.686443        -1826.076904
2023-08-17 23:56:00              0      28.686443        -1822.826416
2023-08-17 23:57:00              0      28.686443         -1827.62561
2023-08-17 23:58:00              0      28.686443        -1825.402466
2023-08-17 23:59:00              0      28.686443        -1823.924561

                    Bihar Total MW Patratu TPS  MW Tenughat TPS  MW  \
2023-08-17 00:00:00     227.477264             0.1       157.449356
2023-08-17 00:01:00     227.477264             0.1       157.449356
2023-08-17 00:02:00     227.477264             0.1       157.449356
2023-08-17 00:03:00     227.477264             0.1       157.449356
2023-08-17 00:04:00     227.477264             0.1       157.449356
...                            ...             ...              ...
2023-08-17 23:55:00              0             0.1       157.449356
2023-08-17 23:56:00              0             0.1       157.449356
2023-08-17 23:57:00              0             0.1       157.449356
2023-08-17 23:58:00              0             0.1       157.449356
2023-08-17 23:59:00              0             0.1       157.449356

                    JH_THERMAL MW  ...  Tala HEP MW Chukha HEP MW DAGACHHU MW  \
2023-08-17 00:00:00    157.549362  ...  1005.427795    117.954483           0
2023-08-17 00:01:00    157.549362  ...  1006.781006    117.477905           0
2023-08-17 00:02:00    157.549362  ...  1008.134216    119.614189           0
2023-08-17 00:03:00    157.549362  ...  1001.368225    119.943703           0
2023-08-17 00:04:00    157.549362  ...  1002.721436    119.673904           0
...                           ...  ...          ...           ...         ...
2023-08-17 23:55:00    157.549362  ...  1002.720764    121.329666           0
2023-08-17 23:56:00    157.549362  ...  1001.368103    121.387062           0
2023-08-17 23:57:00    157.549362  ...  1005.427979    121.804665           0
2023-08-17 23:58:00    157.549362  ...  1002.720764    122.897118           0
2023-08-17 23:59:00    157.549362  ...  1001.368103    121.170639           0

                    MANGDECHU MW BHUTAL_HYDRO_TOTAL MW  \
2023-08-17 00:00:00   442.764404           1645.805176
2023-08-17 00:01:00   444.150299           1645.878906
2023-08-17 00:02:00   443.436646           1651.103516
2023-08-17 00:03:00   443.070526           1643.383789
2023-08-17 00:04:00   442.450378           1646.193848
...                          ...                   ...
2023-08-17 23:55:00     604.2099           1826.076904
2023-08-17 23:56:00    603.72052           1822.826416
2023-08-17 23:57:00   604.021118            1827.62561
2023-08-17 23:58:00   602.978638           1825.402466
2023-08-17 23:59:00   603.921753           1823.924561

                    BARH Stg 1_Unit2(infirm) MW ER_Thermal MW  ER_Hydro MW  \
2023-08-17 00:00:00                  431.913757   25040.09375  6035.372559
2023-08-17 00:01:00                  428.121552   24775.15625  5930.443359
2023-08-17 00:02:00                   426.97879  24811.265625  5943.668457
2023-08-17 00:03:00                  422.480438  24805.009766  5942.525391
2023-08-17 00:04:00                  420.262238  24781.181641  5954.934082
...                                         ...           ...          ...
2023-08-17 23:55:00                  471.328979  24075.873047  6307.470703
2023-08-17 23:56:00                  470.882782  24098.708984  6348.639648
2023-08-17 23:57:00                  469.987396  24115.179688  6352.369141
2023-08-17 23:58:00                  470.470093  24133.291016  6360.104004
2023-08-17 23:59:00                  471.272186  24074.291016  6361.915527

                    ER_SOLAR MW   ER_Total MW
2023-08-17 00:00:00         NaN  31169.998047
2023-08-17 00:01:00         NaN   30799.90625
2023-08-17 00:02:00         NaN  30847.939453
2023-08-17 00:03:00         NaN  30864.443359
2023-08-17 00:04:00         NaN    30834.6875
...                         ...           ...
2023-08-17 23:55:00         NaN  30461.330078
2023-08-17 23:56:00         NaN  30516.496094
2023-08-17 23:57:00         NaN  30545.677734
2023-08-17 23:58:00         NaN  30571.865234
2023-08-17 23:59:00         NaN  30514.400391

[1440 rows x 112 columns]

In [2]:
cwd = os.getcwd()

In [3]:
cwd

'e:\\Applications\\MIS\\mis_be'